
# 此开源项目地址 https://github.com/lowlighter/metrics

name: GitHub lange

on:
  schedule:
    - cron: "0 8 1/2 * *"
    # https://docs.github.com/zh/actions/using-workflows/events-that-trigger-workflows#schedule
  workflow_dispatch:
  workflow_call:
    secrets:
      METRICS_TOKEN:
        required: true
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Node.js 16 (Stable)
        uses: actions/setup-node@v4
        with:
          node-version: '16.x' # Specifies the 16.x branch, which will use the latest stable 16.x release   
      - name: Indepth analysis
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.indepth.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot
          plugin_languages_indepth: yes
          plugin_languages_details: lines, bytes-size
          plugin_languages_limit: 4
          plugin_languages_analysis_timeout: 15

          