name: Social Readme

on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: duanbiao2000/Social-Readme@main
        with:
         
          douban_name: duanbiao2000
          douban_limit: 5 # 豆瓣最新动态数量
          commit_message: Updated social rss by social-readme # commit说明
          
